source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 7.1"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1"
gem "jwt"
gem "rack-cors"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "sqlite3", "~> 1.7"
  gem "debug", platforms: %i[mri windows]
end

group :production do
  gem "pg", "~> 1.5"
end
